apiVersion: apps/v1
kind: Deployment
metadata:
  name: microshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microshop
  template:
    metadata:
      labels:
        app: microshop
    spec:
      containers:
      - name: microshop
        image: nginx
        ports:
        - containerPort: 80
