adminUser: admin
adminPassword: admin123

persistence:
  enabled: true
  storageClassName: managed-premium
  size: 10Gi

service:
  type: ClusterIP
  port: 80

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-operated.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
